/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrays;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void testRoll() {
        int n = 3;

        int [] diceRoll = new int[n+1];
        diceRoll = Library.roll(n);

        assertTrue((diceRoll.length == n));
        
    }
}
