/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void restaurantConstructor() {
        String name = "Chilies";
        int stars = 1;
        String price = "$$$";
        Restaurant chilies = new Restaurant( name,stars,price);
        assertSame(chilies.getName() , name);
    }

    @Test void testCreateReview() {
        String body = "Wow! What a great restaurant";
        String author = "Aurthur Reviewman";
        int score = 5;
        int stars = 1;
        Restaurant whataburger = new Restaurant("Whataburger",stars,"$");
        whataburger.addReview(body,author,score);
        assertSame(whataburger.getReview().author,author);
        assertSame(whataburger.getStars(),(score+stars)/2);
    }

}
