/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrays;

import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println(roll(3));
        return true;
    }

    public static int[] roll(int n) {
        Random rand = new Random();
        int upperBound = 7;
        int[] rollArr = new int[n];

        for (int i = 0; i < rollArr.length; i++) {
            rollArr[i]=rand.nextInt(upperBound);
        }
        return rollArr;
    }

    
}
